[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

; Ces deux lignes activent le hack multicanal dans tout ton projet
build_flags = 
    -D USB_AUDIO
    -D AUDIO_USB_CHANNEL_COUNT=6